DROP TABLE IF EXISTS stars CASCADE;
DROP TABLE IF EXISTS chunks CASCADE;
DROP TABLE IF EXISTS edges CASCADE;
DROP TABLE IF EXISTS entities CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS namespaces CASCADE;
