version: 2

project_name: compass

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - make clean

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"

builds:
  - id: compass
    main: ./main.go
    binary: compass
    flags: [-a]
    ldflags:
      - -X github.com/raystack/compass/cli.Version={{.Tag}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

archives:
  - id: "archives"
    format_overrides:
      - goos: windows
        formats: [zip]

dockers_v2:
  - images:
      - "docker.io/raystack/{{.ProjectName}}"
    tags:
      - "latest"
      - "{{ .Version }}"
      - "{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=release"

nfpms:
  - maintainer: Raystack
    description: Data catalog service
    homepage: https://github.com/raystack/compass
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk

scoops:
  - homepage: "https://github.com/raystack/compass"
    description: "Data catalog service"
    license: Apache 2.0
    repository:
      owner: raystack
      name: scoop-bucket

homebrew_casks:
  - name: compass
    homepage: "https://github.com/raystack/compass"
    description: "Data catalog service"
    repository:
      owner: raystack
      name: homebrew-tap
    license: "Apache 2.0"
    directory: Casks
    install: |-
      bin.install "compass"
    commit_author:
      name: Ravi Suhag
      email: suhag.ravi@gmail.com
