services:
  postgres:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: compass
      POSTGRES_PASSWORD: compass_password
      POSTGRES_DB: compass
    volumes:
      - ./temp/pgdata:/var/lib/postgresql/data
