FROM golang:1.16-stretch as base
WORKDIR /build/
COPY . .
RUN ["make"]

FROM alpine:latest
WORKDIR /opt/compass
COPY --from=base /build/compass /opt/compass/bin/compass
RUN ["apk", "update"]
EXPOSE 8080

# glibc compatibility library, since go binaries 
# don't work well with musl libc that alpine uses
RUN ["apk", "add", "libc6-compat"] 
ENTRYPOINT ["/opt/compass/bin/compass"]