// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	tag "github.com/odpf/columbus/tag"
	mock "github.com/stretchr/testify/mock"
)

// TemplateRepository is an autogenerated mock type for the TemplateRepository type
type TemplateRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: template
func (_m *TemplateRepository) Create(template *tag.Template) error {
	ret := _m.Called(template)

	var r0 error
	if rf, ok := ret.Get(0).(func(*tag.Template) error); ok {
		r0 = rf(template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: filter
func (_m *TemplateRepository) Delete(filter tag.Template) error {
	ret := _m.Called(filter)

	var r0 error
	if rf, ok := ret.Get(0).(func(tag.Template) error); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: filter
func (_m *TemplateRepository) Read(filter tag.Template) ([]tag.Template, error) {
	ret := _m.Called(filter)

	var r0 []tag.Template
	if rf, ok := ret.Get(0).(func(tag.Template) []tag.Template); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.Template)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(tag.Template) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: template
func (_m *TemplateRepository) Update(template *tag.Template) error {
	ret := _m.Called(template)

	var r0 error
	if rf, ok := ret.Get(0).(func(*tag.Template) error); ok {
		r0 = rf(template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
