CREATE TABLE IF NOT EXISTS dead_jobs
(
    id              TEXT      NOT NULL PRIMARY KEY,
    type            TEXT      NOT NULL,
    payload         bytea     NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT current_timestamp,
    updated_at      TIMESTAMP NOT NULL DEFAULT current_timestamp,

    -- Result generated by execution.
    attempts_done   INTEGER   NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP,
    last_error      TEXT
);


CREATE INDEX IF NOT EXISTS idx_dead_jobs_type ON dead_jobs (type);
