ALTER TABLE assets ADD COLUMN IF NOT EXISTS refreshed_at TIMESTAMP;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT false;
ALTER TABLE assets_versions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT false;
