// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	statsd "github.com/goto/compass/pkg/statsd"
	mock "github.com/stretchr/testify/mock"
)

// StatsDClient is an autogenerated mock type for the StatsDClient type
type StatsDClient struct {
	mock.Mock
}

type StatsDClient_Expecter struct {
	mock *mock.Mock
}

func (_m *StatsDClient) EXPECT() *StatsDClient_Expecter {
	return &StatsDClient_Expecter{mock: &_m.Mock}
}

// Histogram provides a mock function with given fields: name, value
func (_m *StatsDClient) Histogram(name string, value float64) *statsd.Metric {
	ret := _m.Called(name, value)

	var r0 *statsd.Metric
	if rf, ok := ret.Get(0).(func(string, float64) *statsd.Metric); ok {
		r0 = rf(name, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*statsd.Metric)
		}
	}

	return r0
}

// StatsDClient_Histogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Histogram'
type StatsDClient_Histogram_Call struct {
	*mock.Call
}

// Histogram is a helper method to define mock.On call
//   - name string
//   - value float64
func (_e *StatsDClient_Expecter) Histogram(name interface{}, value interface{}) *StatsDClient_Histogram_Call {
	return &StatsDClient_Histogram_Call{Call: _e.mock.On("Histogram", name, value)}
}

func (_c *StatsDClient_Histogram_Call) Run(run func(name string, value float64)) *StatsDClient_Histogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *StatsDClient_Histogram_Call) Return(_a0 *statsd.Metric) *StatsDClient_Histogram_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StatsDClient_Histogram_Call) RunAndReturn(run func(string, float64) *statsd.Metric) *StatsDClient_Histogram_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewStatsDClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewStatsDClient creates a new instance of StatsDClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStatsDClient(t mockConstructorTestingTNewStatsDClient) *StatsDClient {
	mock := &StatsDClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
