// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	lineage "github.com/odpf/columbus/lineage/v1"
	mock "github.com/stretchr/testify/mock"
)

// GraphV1 is an autogenerated mock type for the Graph type
type GraphV1 struct {
	mock.Mock
}

// Query provides a mock function with given fields: _a0
func (_m *GraphV1) Query(_a0 lineage.QueryCfg) (lineage.AdjacencyMap, error) {
	ret := _m.Called(_a0)

	var r0 lineage.AdjacencyMap
	if rf, ok := ret.Get(0).(func(lineage.QueryCfg) lineage.AdjacencyMap); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lineage.AdjacencyMap)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(lineage.QueryCfg) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
