// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	lineage "github.com/odpf/columbus/lineage/v1"
	mock "github.com/stretchr/testify/mock"
)

// LineageProvider is an autogenerated mock type for the LineageProvider type
type LineageProvider struct {
	mock.Mock
}

// Graph provides a mock function with given fields:
func (_m *LineageProvider) Graph() (lineage.Graph, error) {
	ret := _m.Called()

	var r0 lineage.Graph
	if rf, ok := ret.Get(0).(func() lineage.Graph); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lineage.Graph)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
