// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	lineage "github.com/odpf/columbus/lineage"
	mock "github.com/stretchr/testify/mock"
)

// LineageRepository is an autogenerated mock type for the Repository type
type LineageRepository struct {
	mock.Mock
}

// GetEdges provides a mock function with given fields: _a0
func (_m *LineageRepository) GetEdges(_a0 context.Context) ([]lineage.Edge, error) {
	ret := _m.Called(_a0)

	var r0 []lineage.Edge
	if rf, ok := ret.Get(0).(func(context.Context) []lineage.Edge); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lineage.Edge)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type LineageProvider struct {
	mock.Mock
}

func (lp *LineageProvider) Graph() (lineage.Graph, error) {
	args := lp.Called()
	return args.Get(0).(lineage.Graph), args.Error(1)
}

type Graph struct {
	mock.Mock
}

func (graph *Graph) Query(cfg lineage.QueryCfg) (lineage.AdjacencyMap, error) {
	args := graph.Called(cfg)
	return args.Get(0).(lineage.AdjacencyMap), args.Error(1)
}
