// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	tag "github.com/odpf/columbus/tag"
	mock "github.com/stretchr/testify/mock"
)

// TagTemplateRepository is an autogenerated mock type for the TagTemplateRepository type
type TagTemplateRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, template
func (_m *TagTemplateRepository) Create(ctx context.Context, template *tag.Template) error {
	ret := _m.Called(ctx, template)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tag.Template) error); ok {
		r0 = rf(ctx, template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, templateURN
func (_m *TagTemplateRepository) Delete(ctx context.Context, templateURN string) error {
	ret := _m.Called(ctx, templateURN)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, templateURN)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: ctx, templateURN
func (_m *TagTemplateRepository) Read(ctx context.Context, templateURN string) ([]tag.Template, error) {
	ret := _m.Called(ctx, templateURN)

	var r0 []tag.Template
	if rf, ok := ret.Get(0).(func(context.Context, string) []tag.Template); ok {
		r0 = rf(ctx, templateURN)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.Template)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, templateURN)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields: ctx
func (_m *TagTemplateRepository) ReadAll(ctx context.Context) ([]tag.Template, error) {
	ret := _m.Called(ctx)

	var r0 []tag.Template
	if rf, ok := ret.Get(0).(func(context.Context) []tag.Template); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.Template)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, templateURN, template
func (_m *TagTemplateRepository) Update(ctx context.Context, templateURN string, template *tag.Template) error {
	ret := _m.Called(ctx, templateURN, template)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *tag.Template) error); ok {
		r0 = rf(ctx, templateURN, template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
