package postgres_test

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/odpf/columbus/store/postgres"
	"github.com/odpf/columbus/user"
	"github.com/ory/dockertest/v3"
	"github.com/sirupsen/logrus"
	"github.com/stretchr/testify/suite"
)

type UserRepositoryTestSuite struct {
	suite.Suite
	ctx        context.Context
	client     *postgres.Client
	pool       *dockertest.Pool
	resource   *dockertest.Resource
	repository *postgres.UserRepository
}

func (r *UserRepositoryTestSuite) SetupSuite() {
	var err error

	logger := logrus.New()
	// logger.SetLevel(logrus.DebugLevel)
	r.client, r.pool, r.resource, err = newTestClient(logger)
	if err != nil {
		logger.Fatal(err)
	}

	r.ctx = context.TODO()
	r.repository, err = postgres.NewUserRepository(r.client)
	if err != nil {
		logger.Fatal(err)
	}
}

func (r *UserRepositoryTestSuite) TearDownSuite() {
	// Clean tests
	err := r.client.Close()
	if err != nil {
		r.T().Fatal(err)
	}
	err = purgeDocker(r.pool, r.resource)
	if err != nil {
		r.T().Fatal(err)
	}
}

func (r *UserRepositoryTestSuite) TestCreate() {
	r.Run("return no error if succesfully create user", func() {
		user := getUser()
		err := r.repository.Create(r.ctx, user)
		r.NoError(err)
	})

	r.Run("return ErrNilUser if user is nil", func() {
		err := r.repository.Create(r.ctx, nil)
		r.ErrorIs(err, user.ErrNilUser)
	})

	r.Run("return ErrDuplicateRecord if user is already exist", func() {
		err := setup(r.ctx, r.client)
		r.NoError(err)

		ud := getUser()
		err = r.repository.Create(r.ctx, ud)
		r.NoError(err)
		err = r.repository.Create(r.ctx, ud)
		r.ErrorAs(err, new(user.DuplicateRecordError))
	})
}

func (r *UserRepositoryTestSuite) TestGetID() {
	r.Run("return empty string and ErrNotFound if email not found in DB", func() {
		uid, err := r.repository.GetID(r.ctx, "random")
		r.ErrorAs(err, new(user.NotFoundError))
		r.Empty(uid)
	})

	r.Run("return non empty id if email found in DB", func() {
		err := setup(r.ctx, r.client)
		r.NoError(err)

		user := getUser()
		err = r.repository.Create(r.ctx, user)
		r.NoError(err)

		uid, err := r.repository.GetID(r.ctx, user.Email)
		r.NoError(err)

		r.NotEmpty(uid)
	})
}

func getUser() *user.User {
	id := uuid.New()
	timestamp := time.Now().UTC()
	return &user.User{
		ID:        id.String(), // uuid is autogenerated in DB
		Email:     "user@odpf.io",
		Provider:  "columbus",
		CreatedAt: timestamp,
		UpdatedAt: timestamp,
	}
}

func TestUserRepository(t *testing.T) {
	suite.Run(t, &UserRepositoryTestSuite{})
}
