log_level: info

db:
    host: localhost
    port: 5432
    name: compass
    user: compass
    password: compass_password
    sslmode: disable

service:
    host: localhost
    port: 8080
    identity:
        headerkey_uuid: Compass-User-UUID
        headerkey_email: Compass-User-Email
        provider_default_name: shield
        namespace_claim_key: project_id

client:
    host: localhost:8080
    serverheaderkey_uuid: Compass-User-UUID
    serverheadervalue_uuid: raystack@email.com
