// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StatsDClient is an autogenerated mock type for the StatsDClient type
type StatsDClient struct {
	mock.Mock
}

type StatsDClient_Expecter struct {
	mock *mock.Mock
}

func (_m *StatsDClient) EXPECT() *StatsDClient_Expecter {
	return &StatsDClient_Expecter{mock: &_m.Mock}
}

// Increment provides a mock function with given fields: _a0
func (_m *StatsDClient) Increment(_a0 string) {
	_m.Called(_a0)
}

// StatsDClient_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type StatsDClient_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//  - _a0 string
func (_e *StatsDClient_Expecter) Increment(_a0 interface{}) *StatsDClient_Increment_Call {
	return &StatsDClient_Increment_Call{Call: _e.mock.On("Increment", _a0)}
}

func (_c *StatsDClient_Increment_Call) Run(run func(_a0 string)) *StatsDClient_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StatsDClient_Increment_Call) Return() *StatsDClient_Increment_Call {
	_c.Call.Return()
	return _c
}

// Timing provides a mock function with given fields: _a0, _a1
func (_m *StatsDClient) Timing(_a0 string, _a1 int64) {
	_m.Called(_a0, _a1)
}

// StatsDClient_Timing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Timing'
type StatsDClient_Timing_Call struct {
	*mock.Call
}

// Timing is a helper method to define mock.On call
//  - _a0 string
//  - _a1 int64
func (_e *StatsDClient_Expecter) Timing(_a0 interface{}, _a1 interface{}) *StatsDClient_Timing_Call {
	return &StatsDClient_Timing_Call{Call: _e.mock.On("Timing", _a0, _a1)}
}

func (_c *StatsDClient_Timing_Call) Run(run func(_a0 string, _a1 int64)) *StatsDClient_Timing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64))
	})
	return _c
}

func (_c *StatsDClient_Timing_Call) Return() *StatsDClient_Timing_Call {
	_c.Call.Return()
	return _c
}
